/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPrincipal.java
 *
 * Created on 02/06/2010, 13:02:00
 */
package gestaocantina;

import Classes.ACP;
import Classes.DadosMes;
import Classes.Produto;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jxl.*;
import jxl.read.biff.BiffException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Katha
 */
public class FormPrincipal extends javax.swing.JFrame {

    /** Creates new form FormPrincipal */
    public FormPrincipal() {
        initComponents();
        this.setSize(500, 500);
        acp = new ACP();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAbrirPlanilha = new javax.swing.JButton();
        txtCaminho = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDados = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ltituloCurvaABC = new javax.swing.JLabel();
        lCurva = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnAbrirPlanilha.setText("Abrir");
        btnAbrirPlanilha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirPlanilhaMouseClicked(evt);
            }
        });
        jPanel1.add(btnAbrirPlanilha, java.awt.BorderLayout.LINE_END);

        txtCaminho.setText("Gestao Cantina.xls");
        txtCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaminhoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCaminho, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Arquivo:  ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestão de Estoque");
        jPanel1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanelDados.setLayout(new java.awt.BorderLayout());
        jPanelDados.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qtd Estoque", "Custo Unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelDados.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Dados", jPanelDados);

        jPanel3.setLayout(new java.awt.BorderLayout());

        ltituloCurvaABC.setText("Curva ABC");
        jPanel3.add(ltituloCurvaABC, java.awt.BorderLayout.PAGE_START);

        lCurva.setText("Curva");
        jPanel3.add(lCurva, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Curva ABC", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Política:   ");
        jPanel5.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lote Econômico de Pedidos", "Revisão Contínua", "Sistemas de Revisão Periódica" }));
        jPanel5.add(jComboBox1, java.awt.BorderLayout.CENTER);

        jButton2.setText("Gerar");
        jPanel5.add(jButton2, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Exibir resultado aqui");
        jPanel6.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Políticas de Estoque", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MRP", jPanel7);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaminhoActionPerformed

    private void btnAbrirPlanilhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirPlanilhaMouseClicked
        // TODO add your handling code here:
        String caminhoArquivo = txtCaminho.getText();
        if (!caminhoArquivo.equals("")) {
            ArrayList<Produto> produtos = carregarDados(caminhoArquivo);
            acp.setProdutos(produtos);
            jTableProduto.removeAll();

            DefaultTableModel dtm = (DefaultTableModel) jTableProduto.getModel();
            DecimalFormat format = new DecimalFormat();
            format.setMaximumFractionDigits(2);
            format.setMinimumFractionDigits(2);

            for (int i = 0; i < produtos.size(); i++) {
                Produto p = produtos.get(i);
                ArrayList<DadosMes> dados = p.getHistorico();
                double dCusto = p.getValorUnitCusto();

                dtm.addRow(new Object[]{p.getNome(), p.getQtdAtual(), format.format(dCusto)});
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe o caminho do arquivo !", nomeSistema, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAbrirPlanilhaMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if (acp.getProdutos().isEmpty()) {
            ltituloCurvaABC.setText("Erro: Carregue o arquivo de dados!");
        } else {
            ltituloCurvaABC.setText("Curva ABC");
            acp.gerarABC();
            this.gerarGrafico();
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void gerarGrafico() {
        ArrayList<Produto> produtos = acp.getProdutos();
        double acumulada = 0.0;
        double dI = 0.0;
        
        XYSeries series = new XYSeries("");
        for(int i = 0; i < produtos.size(); i++){
            acumulada += produtos.get(i).getPorcentagem()*100;
            dI += 1.0;
            series.add(acumulada, dI);
        /*while(produtos.get(i).getTipo() == 0)
            i++;
        series.add(produtos.get(i).getPorcentagem()*100, 5.0);
        while(produtos.get(i).getTipo() == 1)
            i++;
        series.add(produtos.get(i).getPorcentagem()*100, 10.0);*/
        }
        XYDataset xyDataset = new XYSeriesCollection(series);
        
        JFreeChart chart = ChartFactory.createXYAreaChart("Curva ABC", "Porcentagem", "Produto", xyDataset, PlotOrientation.HORIZONTAL, true, false, false);

        BufferedImage image = chart.createBufferedImage(800, 300);
        
        lCurva.setIcon(new ImageIcon(image));
        lCurva.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    private ArrayList<Produto> carregarDados(String caminhoArquivo) {
        ArrayList<Produto> produtos = new ArrayList<Produto>();
        try {
            Workbook workbook = Workbook.getWorkbook(new File(caminhoArquivo));
            Sheet sheet = workbook.getSheet("CONTROLE");

            //Le número de linhas preenchidas na planilha
            Cell cell = sheet.getCell("IV1");
            String sNumLinhas = cell.getContents();
            int iNumLinhas = Integer.parseInt(sNumLinhas);

            //Le número de colunas preenchidas na planilha
            cell = sheet.getCell("IV2");
            String sNumColunas = cell.getContents();
            int iNumColunas = Integer.parseInt(sNumColunas);

            for (int lin = 2; lin < iNumLinhas; lin++) {
                int col2 = 0;
                int col;

                //Le nome do produto
                cell = sheet.getCell(col2, lin);
                Produto produto = new Produto();
                produto.setNome(cell.getContents());
                ArrayList<DadosMes> dadosmes = new ArrayList<DadosMes>();

                System.out.println("Produto " + produto.getNome());

                NumberCell ncell;

                for (col = col2 + 1; col < iNumColunas - 2; col++) {
                    DadosMes dados = new DadosMes();
                    //Le mês
                    cell = sheet.getCell(col, 0);
                    String sMes = cell.getContents();
                    dados.setMes(sMes);
                    System.out.print("    Mes " + dados.getMes());

                    //Le ano
                    ncell = (NumberCell) sheet.getCell(col + 1, 0);
                    dados.setAno((int) ncell.getValue());
                    System.out.println("    Ano " + dados.getAno());

                    //Le qtde comprada
                    ncell = (NumberCell) sheet.getCell(col, lin);
                    dados.setQtdCompra((int) ncell.getValue());
                    col++;
                    System.out.println("        Qtde Comp  " + dados.getQtdCompra());

                    //Le preço de custo
                    ncell = (NumberCell) sheet.getCell(col, lin);
                    produto.setValorUnitCusto(ncell.getValue());
                    col++;
                    System.out.println("        Custo Unit " + produto.getValorUnitCusto());

                    //Le qtde venda
                    ncell = (NumberCell) sheet.getCell(col, lin);
                    dados.setQtdVenda((int) ncell.getValue());
                    col++;
                    System.out.println("        Qtde Venda " + dados.getQtdVenda());

                    //Le preço de venda
                    ncell = (NumberCell) sheet.getCell(col, lin);
                    produto.setValorUnitVenda(ncell.getValue());
                    System.out.println("        Preco Unit " + produto.getValorUnitVenda());

                    produto.addHistorico(dados);
                }

                //Le qtde atual
                ncell = (NumberCell) sheet.getCell(col, lin);
                produto.setQtdAtual((int) ncell.getValue());
                col++;
                System.out.println("    Qtd " + produto.getQtdAtual());

                //Le estoque de seguranca
                ncell = (NumberCell) sheet.getCell(col, lin);
                produto.setQtdSeguranca((int) ncell.getValue());
                System.out.println("    Sec " + produto.getQtdSeguranca());

                produtos.add(produto);
            }

            workbook.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Erro ao ler " + caminhoArquivo, nomeSistema, JOptionPane.ERROR_MESSAGE);
        }

        System.out.println("fim");

        return produtos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPlanilha;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lCurva;
    private javax.swing.JLabel ltituloCurvaABC;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
    private final String nomeSistema = "Gestão Cantina";
    private ACP acp;
}
